version: "3.9"
services:
  rtsp:
    build: 
      context: ./rtsp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  inference:
    build: 
      context: ./inference
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rtsp
